buildscript {
    ext.kotlin_version = '1.7.22'
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public/' }
        maven {
            url 'https://maven.aliyun.com/nexus/content/groups/public/'
        }
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven {
            url 'https://maven.aliyun.com/repository/public/'
        }
        maven { url 'https://jitpack.io' }
        maven {
            url 'https://maven.aliyun.com/nexus/content/groups/public/'
        }
        google()
        mavenCentral()
        maven {
            url 'http://123.56.84.239:8070/nexus/content/groups/public'
            allowInsecureProtocol = true
        }
        maven {
            url 'https://maven.aliyun.com/nexus/content/repositories/releases/'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
